preload = /home/turtle/Pictures/Wallpapers/Wallpaper.jpg
preload = /home/turtle/Pictures/Wallpapers/wallpaper-1.jpg
preload = /home/turtle/Pictures/Wallpapers/wallpaper-2.jpg
preload = /home/turtle/Pictures/Wallpapers/wallpaper-3.jpg
wallpaper = ,/home/turtle/Pictures/Wallpapers/wallpaper-1.jpg
ipc = on
